/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface MyComponentProps {
  text: string;
}

function MyComponent({ text }: MyComponentProps) {
  return (
    <h1 className="text-5xl font-black text-cyan-600 tracking-[2.08px] max-md:max-w-full max-md:text-4xl">
      {text}
    </h1>
  );
}

export default MyComponent;