/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

interface MenuItemProps {
  label: string;
  isActive?: boolean;
}

const MenuItem: React.FC<MenuItemProps> = ({ label, isActive = false }) => {
  const baseClasses =
    "justify-center px-3 py-1 whitespace-nowrap bg-white rounded-lg";
  const activeClasses = isActive ? "font-semibold text-sky-500 shadow-sm" : "";

  return <div className={`${baseClasses} ${activeClasses}`}>{label}</div>;
};

const menuItems = [
  { label: "Home", isActive: true },
  { label: "Features" },
  { label: "About" },
  { label: "Contact Us" },
  { label: "Blogs" },
  { label: "FAQ" },
];

const MyComponent: React.FC = () => {
  return (
    <div className="flex flex-col items-center px-16 pt-9 w-full bg-white max-md:px-5 max-md:max-w-full">
      <div className="flex flex-col w-full max-w-[1122px] max-md:max-w-full">
        <header className="flex gap-3 justify-between px-px w-full text-sm leading-5 text-zinc-500 max-md:flex-wrap max-md:max-w-full">
          <img
            loading="lazy"
            src="https://cdn.builder.io/api/v1/image/assets/TEMP/ee7998aded1d35939e9766f233445c917326ecd4bbe9e032d4615347e5ea8a8e?apiKey=706b7444b4d24b608a36b188095816f8&"
            alt="Company logo"
            className="shrink-0 my-auto aspect-[5.26] w-[83px]"
          />
          <nav className="flex gap-4 max-md:flex-wrap">
            {menuItems.map((item) => (
              <MenuItem
                key={item.label}
                label={item.label}
                isActive={item.isActive}
              />
            ))}
          </nav>
        </header>
        <main className="mt-24 max-md:mt-10 max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col max-md:gap-0">
            <section className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col max-md:mt-3 max-md:max-w-full">
                <h1 className="text-5xl font-black text-cyan-600 tracking-[2.08px] max-md:max-w-full max-md:text-4xl">
                  Connecting Paths, Progressing Together
                </h1>
                <p className="mt-2 text-lg font-medium leading-6 text-zinc-600 max-md:max-w-full">
                  - Your Bridge to Seamless Neuro-Diverse Care.
                </p>
                <div className="flex gap-4 self-start mt-8 text-xl font-semibold leading-7 text-center">
                  <button className="justify-center px-4 py-1.5 text-white bg-sky-500 rounded-md">
                    Sign Up
                  </button>
                  <button className="flex gap-1 justify-center px-0.5 py-1.5 text-sky-500 rounded-lg">
                    <span>Book Demo</span>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/9997966c3f7d84ab1be7b4f12e5e21cd277902445b5e16c02aa59e76d02b304d?apiKey=706b7444b4d24b608a36b188095816f8&"
                      alt=""
                      className="shrink-0 my-auto w-4 aspect-square"
                    />
                  </button>
                </div>
              </div>
            </section>
            <section className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow px-6 pt-6 w-full rounded-xl bg-neutral-100 max-md:px-5 max-md:mt-3 max-md:max-w-full">
                <div className="max-md:max-w-full">
                  <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                    <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/bef0dd64a59c4070edcf53149253a668cc9a436d101edfafa3fa764a6168d26a?apiKey=706b7444b4d24b608a36b188095816f8&"
                        alt="Image 1"
                        className="grow w-full aspect-[1.06] max-md:mt-5"
                      />
                    </div>
                    <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/554d79f5084dc568610f5370b814d7ef4051c0056731993b056a1c735bd1e0ed?apiKey=706b7444b4d24b608a36b188095816f8&"
                        alt="Image 2"
                        className="grow w-full aspect-[1.06] max-md:mt-5"
                      />
                    </div>
                  </div>
                </div>
                <img
                  loading="lazy"
                  src="https://cdn.builder.io/api/v1/image/assets/TEMP/b7f120cd0360b190d78fdb89f712b4e2160af3427838e57acec978b28f342591?apiKey=706b7444b4d24b608a36b188095816f8&"
                  alt="Image 3"
                  className="mt-6 w-full aspect-[2.22] max-md:max-w-full"
                />
              </div>
            </section>
          </div>
        </main>
      </div>
    </div>
  );
};

export default MyComponent;
