/**
 * This code was generated by Builder.io.
 */
import * as React from "react";

function MyComponent() {
  return (
    <div className="flex flex-col pointer-events-auto">
      <div className="flex flex-col items-center px-16 pt-9 w-full bg-white max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col w-full max-w-[1122px] max-md:max-w-full">
          <div className="flex gap-3 justify-between px-px w-full text-sm leading-5 text-zinc-500 max-md:flex-wrap max-md:max-w-full">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/ee7998aded1d35939e9766f233445c917326ecd4bbe9e032d4615347e5ea8a8e?apiKey=706b7444b4d24b608a36b188095816f8&"
              className="shrink-0 my-auto aspect-[5.26] w-[83px]"
            />
            <div className="flex gap-4 max-md:flex-wrap">
              <div className="justify-center px-3 py-1 font-semibold text-sky-500 whitespace-nowrap bg-white rounded-lg shadow-sm">
                Home
              </div>
              <div className="justify-center px-3 py-1 whitespace-nowrap bg-white rounded-lg">
                Features
              </div>
              <div className="justify-center px-3 py-1 whitespace-nowrap bg-white rounded-lg">
                About
              </div>
              <div className="justify-center px-3 py-1 bg-white rounded-lg">
                Contact Us
              </div>
              <div className="justify-center px-3 py-1 whitespace-nowrap bg-white rounded-lg">
                Blogs
              </div>
              <div className="justify-center px-3 py-1 whitespace-nowrap bg-white rounded-lg">
                FAQ
              </div>
            </div>
          </div>
          <div className="mt-24 max-md:mt-10 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                <div className="flex flex-col max-md:mt-3 max-md:max-w-full">
                  <div className="text-5xl font-black text-cyan-600 tracking-[2.08px] max-md:max-w-full max-md:text-4xl">
                    Connecting Paths, Progressing Together
                  </div>
                  <div className="mt-2 text-lg font-medium leading-6 text-zinc-600 max-md:max-w-full">
                    - Your Bridge to Seamless Neuro-Diverse Care.
                  </div>
                  <div className="flex gap-4 self-start mt-8 text-xl font-semibold leading-7 text-center">
                    <div className="justify-center px-4 py-1.5 text-white bg-sky-500 rounded-md">
                      Sign Up
                    </div>
                    <div className="flex gap-1 justify-center px-0.5 py-1.5 text-sky-500 rounded-lg">
                      <div>Book Demo</div>
                      <img
                        loading="lazy"
                        src="https://cdn.builder.io/api/v1/image/assets/TEMP/9997966c3f7d84ab1be7b4f12e5e21cd277902445b5e16c02aa59e76d02b304d?apiKey=706b7444b4d24b608a36b188095816f8&"
                        className="shrink-0 my-auto w-4 aspect-square"
                      />
                    </div>
                  </div>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow px-6 pt-6 w-full rounded-xl bg-neutral-100 max-md:px-5 max-md:mt-3 max-md:max-w-full">
                  <div className="max-md:max-w-full">
                    <div className="flex gap-5 max-md:flex-col max-md:gap-0">
                      <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
                        <img
                          loading="lazy"
                          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/bef0dd64a59c4070edcf53149253a668cc9a436d101edfafa3fa764a6168d26a?apiKey=706b7444b4d24b608a36b188095816f8&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/bef0dd64a59c4070edcf53149253a668cc9a436d101edfafa3fa764a6168d26a?apiKey=706b7444b4d24b608a36b188095816f8&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/bef0dd64a59c4070edcf53149253a668cc9a436d101edfafa3fa764a6168d26a?apiKey=706b7444b4d24b608a36b188095816f8&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/bef0dd64a59c4070edcf53149253a668cc9a436d101edfafa3fa764a6168d26a?apiKey=706b7444b4d24b608a36b188095816f8&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/bef0dd64a59c4070edcf53149253a668cc9a436d101edfafa3fa764a6168d26a?apiKey=706b7444b4d24b608a36b188095816f8&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/bef0dd64a59c4070edcf53149253a668cc9a436d101edfafa3fa764a6168d26a?apiKey=706b7444b4d24b608a36b188095816f8&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/bef0dd64a59c4070edcf53149253a668cc9a436d101edfafa3fa764a6168d26a?apiKey=706b7444b4d24b608a36b188095816f8&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/bef0dd64a59c4070edcf53149253a668cc9a436d101edfafa3fa764a6168d26a?apiKey=706b7444b4d24b608a36b188095816f8&"
                          className="grow w-full aspect-[1.06] max-md:mt-5"
                        />
                      </div>
                      <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
                        <img
                          loading="lazy"
                          srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/554d79f5084dc568610f5370b814d7ef4051c0056731993b056a1c735bd1e0ed?apiKey=706b7444b4d24b608a36b188095816f8&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/554d79f5084dc568610f5370b814d7ef4051c0056731993b056a1c735bd1e0ed?apiKey=706b7444b4d24b608a36b188095816f8&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/554d79f5084dc568610f5370b814d7ef4051c0056731993b056a1c735bd1e0ed?apiKey=706b7444b4d24b608a36b188095816f8&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/554d79f5084dc568610f5370b814d7ef4051c0056731993b056a1c735bd1e0ed?apiKey=706b7444b4d24b608a36b188095816f8&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/554d79f5084dc568610f5370b814d7ef4051c0056731993b056a1c735bd1e0ed?apiKey=706b7444b4d24b608a36b188095816f8&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/554d79f5084dc568610f5370b814d7ef4051c0056731993b056a1c735bd1e0ed?apiKey=706b7444b4d24b608a36b188095816f8&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/554d79f5084dc568610f5370b814d7ef4051c0056731993b056a1c735bd1e0ed?apiKey=706b7444b4d24b608a36b188095816f8&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/554d79f5084dc568610f5370b814d7ef4051c0056731993b056a1c735bd1e0ed?apiKey=706b7444b4d24b608a36b188095816f8&"
                          className="grow w-full aspect-[1.06] max-md:mt-5"
                        />
                      </div>
                    </div>
                  </div>
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/b7f120cd0360b190d78fdb89f712b4e2160af3427838e57acec978b28f342591?apiKey=706b7444b4d24b608a36b188095816f8&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7f120cd0360b190d78fdb89f712b4e2160af3427838e57acec978b28f342591?apiKey=706b7444b4d24b608a36b188095816f8&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7f120cd0360b190d78fdb89f712b4e2160af3427838e57acec978b28f342591?apiKey=706b7444b4d24b608a36b188095816f8&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7f120cd0360b190d78fdb89f712b4e2160af3427838e57acec978b28f342591?apiKey=706b7444b4d24b608a36b188095816f8&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7f120cd0360b190d78fdb89f712b4e2160af3427838e57acec978b28f342591?apiKey=706b7444b4d24b608a36b188095816f8&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7f120cd0360b190d78fdb89f712b4e2160af3427838e57acec978b28f342591?apiKey=706b7444b4d24b608a36b188095816f8&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7f120cd0360b190d78fdb89f712b4e2160af3427838e57acec978b28f342591?apiKey=706b7444b4d24b608a36b188095816f8&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/b7f120cd0360b190d78fdb89f712b4e2160af3427838e57acec978b28f342591?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="mt-6 w-full aspect-[2.22] max-md:max-w-full"
                  />
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex z-10 justify-center items-center px-16 py-20 w-full bg-neutral-100 max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col my-4 w-full max-w-[1120px] max-md:max-w-full">
          <div className="flex flex-col self-start pl-4 border-l-2 border-sky-500 border-solid">
            <div className="text-base leading-8 uppercase text-zinc-500">
              Services
            </div>
            <div className="text-4xl font-semibold leading-8 text-cyan-900">
              Things we provide
            </div>
          </div>
          <div className="mt-5 ml-4 text-base leading-6 text-zinc-600 w-[545px] max-md:max-w-full">
            Elevate Your Business: Tailored Mental Health Solutions. Partner
            with us for top-tier care tailored to your team&apos;s needs.
          </div>
          <div className="mt-10 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow justify-between px-6 py-10 w-full text-lg font-semibold leading-6 bg-white rounded-xl border border-gray-200 border-solid text-zinc-600 max-md:px-5 max-md:mt-7">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/006caacb01853d2e4b6527c1ed6886e761811b83ab6190be9632df0bf4273c79?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="aspect-square w-[78px]"
                  />
                  <div className="mt-12 max-md:mt-10">
                    Personalized Online Booking
                  </div>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow justify-between px-6 py-10 w-full text-lg font-semibold leading-6 bg-white rounded-xl border border-gray-200 border-solid text-zinc-600 max-md:px-5 max-md:mt-7">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/a56e51e9b0417af8c6a57cf377b19d57a7080c579461b9fe35aaf6cd14a78fae?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="aspect-square w-[78px]"
                  />
                  <div className="mt-12 max-md:mt-10">
                    Synchronized Calendars
                  </div>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow justify-between px-6 py-10 w-full text-lg font-semibold leading-6 bg-white rounded-xl border border-gray-200 border-solid text-zinc-600 max-md:px-5 max-md:mt-7">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/965fe84f1a9df3720bc5b80a036cc5aa8b90b985320a6a9480cf256f4d8eea02?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="aspect-square w-[78px]"
                  />
                  <div className="mt-12 max-md:mt-10">
                    Compassionate Patient Care
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="mt-6 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-3/12 max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow justify-between px-6 py-10 w-full text-lg font-semibold leading-7 bg-white rounded-xl border border-gray-200 border-solid text-zinc-600 max-md:px-5 max-md:mt-5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/9d6f86e4a17353e672dc604a54a673ffd8b30ab779981ff0b2459485d7463aa1?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="aspect-square w-[78px]"
                  />
                  <div className="mt-4">
                    Insightful Business Performance Analysis
                  </div>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow justify-between px-6 py-10 w-full text-lg font-semibold leading-7 bg-white rounded-xl border border-gray-200 border-solid text-zinc-600 max-md:px-5 max-md:mt-5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/2fa19a79dc187301894c8e271c681fad3468db5e2f96cc5155f715930dceae29?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="aspect-square w-[78px]"
                  />
                  <div className="mt-5">Hassle-Free Online Payments</div>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow justify-between px-6 py-10 w-full text-lg font-semibold leading-7 bg-white rounded-xl border border-gray-200 border-solid text-zinc-600 max-md:px-5 max-md:mt-5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/012b3063ae5c2bdfc74d5e4b0dea0d5ddcb93e024ce3b34a80e60cc52630c3b3?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="aspect-square w-[78px]"
                  />
                  <div className="mt-5">Flexible Employee Coordination</div>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-3/12 max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow justify-between px-6 py-10 w-full text-lg font-semibold leading-7 bg-white rounded-xl border border-gray-200 border-solid text-zinc-600 max-md:px-5 max-md:mt-5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/d7d68c5dd47d32e99ce725ac83364e99dc2f0bd8bb80b5d89fb8aa3518fca121?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="aspect-square w-[78px]"
                  />
                  <div className="mt-5">Empathetic Task Automation</div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex justify-center items-center px-16 py-20 w-full bg-white max-md:px-5 max-md:max-w-full">
        <div className="mt-4 mb-3.5 w-full max-w-[1118px] max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col max-md:gap-0">
            <div className="flex flex-col w-2/5 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col max-md:mt-10 max-md:max-w-full">
                <div className="flex flex-col pl-4 border-l-2 border-sky-500 border-solid max-md:pl-5 max-md:max-w-full">
                  <div className="text-base leading-8 uppercase text-zinc-500">
                    About Us
                  </div>
                  <div className="text-4xl font-semibold leading-8 text-cyan-900">
                    What is RXPIN?
                  </div>
                </div>
                <div className="flex flex-col pl-4 mt-5 text-sm max-md:max-w-full">
                  <div className="leading-5 text-zinc-600">
                    RxPIN is a specialized communication and synchronization
                    platform designed for therapists, patients, and guardians
                    within the neuro-divergent community. It streamlines therapy
                    coordination by offering secure communication, real-time
                    teletherapy sessions (planned), progress tracking, roster
                    management, and billing support.
                  </div>
                  <div className="flex gap-1 justify-center self-start px-0.5 py-1.5 mt-5 font-semibold text-center text-sky-500 rounded-lg leading-[143%]">
                    <div>Read more</div>
                    <img
                      loading="lazy"
                      src="https://cdn.builder.io/api/v1/image/assets/TEMP/9997966c3f7d84ab1be7b4f12e5e21cd277902445b5e16c02aa59e76d02b304d?apiKey=706b7444b4d24b608a36b188095816f8&"
                      className="shrink-0 my-auto w-4 aspect-square"
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-3/5 max-md:ml-0 max-md:w-full">
              <img
                loading="lazy"
                srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/fe5aef60140b98ec8bdc8961a87d6ff0a7edb736a784fcf5b7a4d0887f772e37?apiKey=706b7444b4d24b608a36b188095816f8&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/fe5aef60140b98ec8bdc8961a87d6ff0a7edb736a784fcf5b7a4d0887f772e37?apiKey=706b7444b4d24b608a36b188095816f8&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fe5aef60140b98ec8bdc8961a87d6ff0a7edb736a784fcf5b7a4d0887f772e37?apiKey=706b7444b4d24b608a36b188095816f8&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/fe5aef60140b98ec8bdc8961a87d6ff0a7edb736a784fcf5b7a4d0887f772e37?apiKey=706b7444b4d24b608a36b188095816f8&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/fe5aef60140b98ec8bdc8961a87d6ff0a7edb736a784fcf5b7a4d0887f772e37?apiKey=706b7444b4d24b608a36b188095816f8&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/fe5aef60140b98ec8bdc8961a87d6ff0a7edb736a784fcf5b7a4d0887f772e37?apiKey=706b7444b4d24b608a36b188095816f8&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/fe5aef60140b98ec8bdc8961a87d6ff0a7edb736a784fcf5b7a4d0887f772e37?apiKey=706b7444b4d24b608a36b188095816f8&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/fe5aef60140b98ec8bdc8961a87d6ff0a7edb736a784fcf5b7a4d0887f772e37?apiKey=706b7444b4d24b608a36b188095816f8&"
                className="grow mt-20 w-full border border-gray-200 border-solid aspect-[1.96] max-md:mt-10 max-md:max-w-full"
              />
            </div>
          </div>
        </div>
      </div>
      <div className="flex justify-center items-center px-16 py-20 w-full bg-cyan-800 max-md:px-5 max-md:max-w-full">
        <div className="mt-4 mb-1 w-full max-w-[1061px] max-md:max-w-full">
          <div className="flex gap-5 max-md:flex-col max-md:gap-0">
            <div className="flex flex-col w-6/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col items-start max-md:mt-10 max-md:max-w-full">
                <div className="flex flex-col self-stretch pl-4 border-l-2 border-sky-500 border-solid max-md:max-w-full">
                  <div className="text-base leading-8 uppercase text-zinc-300 max-md:max-w-full">
                    Contact us
                  </div>
                  <div className="text-4xl font-semibold leading-8 text-slate-50 max-md:max-w-full">
                    Get in touch with us
                  </div>
                </div>
                <div className="flex gap-3 mt-12 ml-4 text-white max-md:flex-wrap max-md:mt-10">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/1423bbeebe7df0c3e8fe1426fd57973510a3db70083410ed2f19b134125aa872?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="shrink-0 self-start w-6 aspect-square"
                  />
                  <div className="flex flex-col py-1.5">
                    <div className="text-base leading-6">Our Location</div>
                    <div className="mt-5 text-lg font-medium leading-6">
                      Building 123, ABC Street, Lalitpur, Nepal, 44700{" "}
                    </div>
                  </div>
                </div>
                <div className="flex gap-3 mt-8 ml-4 text-white max-md:flex-wrap">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/65decac00fe1cd87675016a684f7191a4ee0914da1e8bd6ba4585b0dce983084?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="shrink-0 self-start w-6 aspect-square"
                  />
                  <div className="flex flex-col py-1.5">
                    <div className="text-base leading-6">Phone Number</div>
                    <div className="mt-5 text-lg font-medium leading-6">
                      +977-9876543211 | +977-01- 5443123
                    </div>
                  </div>
                </div>
                <div className="flex gap-3 mt-8 ml-4 text-white max-md:ml-2.5">
                  <img
                    loading="lazy"
                    src="https://cdn.builder.io/api/v1/image/assets/TEMP/04c1dfc7a9741dc898a7e1d2abb001a1cc9f8acfc48cb5b1326e225386782e8b?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="shrink-0 self-start w-6 aspect-square"
                  />
                  <div className="flex flex-col py-1.5">
                    <div className="text-base leading-6">Email us on</div>
                    <div className="mt-5 text-lg font-medium leading-6">
                      connect@rxpin.com
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex flex-col ml-5 w-6/12 max-md:ml-0 max-md:w-full">
              <div className="flex flex-col grow justify-end p-9 w-full text-sm font-medium leading-5 rounded-lg border border-solid shadow-sm bg-white bg-opacity-10 border-slate-500 text-zinc-100 max-md:px-5 max-md:mt-10 max-md:max-w-full">
                <div className="justify-center items-start px-3 py-1 rounded-lg border border-gray-200 border-solid max-md:pr-5">
                  Full name
                </div>
                <div className="justify-center items-start px-3 py-1 mt-4 rounded-lg border border-gray-200 border-solid max-md:pr-5">
                  Email Address
                </div>
                <div className="justify-center items-start px-3 py-1 mt-4 rounded-lg border border-gray-200 border-solid max-md:pr-5">
                  Phone Number (Optional)
                </div>
                <div className="justify-center items-start px-3 pt-1 pb-5 mt-4 whitespace-nowrap rounded-lg border border-gray-200 border-solid max-md:pr-5">
                  Message
                </div>
                <div className="justify-center items-center px-4 py-1.5 mt-4 font-semibold text-center text-cyan-800 whitespace-nowrap bg-white rounded-md max-md:px-5">
                  Submit
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className="flex z-10 justify-center items-center px-16 py-20 w-full bg-stone-50 max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col my-4 w-full max-w-[1123px] max-md:max-w-full">
          <div className="flex flex-col self-start pl-4 border-l-2 border-sky-500 border-solid max-md:max-w-full">
            <div className="text-base leading-8 uppercase text-zinc-500 max-md:max-w-full">
              RXPIN Blogs
            </div>
            <div className="text-4xl font-semibold leading-8 text-cyan-900 max-md:max-w-full">
              Recent Information on health and technology
            </div>
          </div>
          <div className="mt-12 max-md:mt-10 max-md:max-w-full">
            <div className="flex gap-5 max-md:flex-col max-md:gap-0">
              <div className="flex flex-col w-[33%] max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow px-3 pt-3 pb-5 w-full text-base font-semibold leading-6 bg-white rounded-xl border border-solid border-zinc-100 text-zinc-600 max-md:mt-2.5">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/3b7ec2639fa99f60036daadce16bd3eeabc31ba1b10025509e4b38f5c9a63e93?apiKey=706b7444b4d24b608a36b188095816f8&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/3b7ec2639fa99f60036daadce16bd3eeabc31ba1b10025509e4b38f5c9a63e93?apiKey=706b7444b4d24b608a36b188095816f8&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/3b7ec2639fa99f60036daadce16bd3eeabc31ba1b10025509e4b38f5c9a63e93?apiKey=706b7444b4d24b608a36b188095816f8&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/3b7ec2639fa99f60036daadce16bd3eeabc31ba1b10025509e4b38f5c9a63e93?apiKey=706b7444b4d24b608a36b188095816f8&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/3b7ec2639fa99f60036daadce16bd3eeabc31ba1b10025509e4b38f5c9a63e93?apiKey=706b7444b4d24b608a36b188095816f8&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/3b7ec2639fa99f60036daadce16bd3eeabc31ba1b10025509e4b38f5c9a63e93?apiKey=706b7444b4d24b608a36b188095816f8&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/3b7ec2639fa99f60036daadce16bd3eeabc31ba1b10025509e4b38f5c9a63e93?apiKey=706b7444b4d24b608a36b188095816f8&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/3b7ec2639fa99f60036daadce16bd3eeabc31ba1b10025509e4b38f5c9a63e93?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="w-full aspect-[1.54]"
                  />
                  <div className="mt-6">
                    Enhancing Cognitive Growth: Strategies for Mental
                    Development
                  </div>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow px-3 pt-3 pb-5 w-full text-base font-semibold leading-6 bg-white rounded-xl border border-solid border-zinc-100 text-zinc-600 max-md:mt-2.5">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/8a8ed9de28846f80fd6c2c53c5cd24b551f95993050fb76f535bd3d1a3932c2a?apiKey=706b7444b4d24b608a36b188095816f8&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a8ed9de28846f80fd6c2c53c5cd24b551f95993050fb76f535bd3d1a3932c2a?apiKey=706b7444b4d24b608a36b188095816f8&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a8ed9de28846f80fd6c2c53c5cd24b551f95993050fb76f535bd3d1a3932c2a?apiKey=706b7444b4d24b608a36b188095816f8&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a8ed9de28846f80fd6c2c53c5cd24b551f95993050fb76f535bd3d1a3932c2a?apiKey=706b7444b4d24b608a36b188095816f8&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a8ed9de28846f80fd6c2c53c5cd24b551f95993050fb76f535bd3d1a3932c2a?apiKey=706b7444b4d24b608a36b188095816f8&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a8ed9de28846f80fd6c2c53c5cd24b551f95993050fb76f535bd3d1a3932c2a?apiKey=706b7444b4d24b608a36b188095816f8&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a8ed9de28846f80fd6c2c53c5cd24b551f95993050fb76f535bd3d1a3932c2a?apiKey=706b7444b4d24b608a36b188095816f8&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/8a8ed9de28846f80fd6c2c53c5cd24b551f95993050fb76f535bd3d1a3932c2a?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="w-full aspect-[1.54]"
                  />
                  <div className="mt-6">
                    Enhancing Cognitive Growth: Strategies for Mental
                    Development
                  </div>
                </div>
              </div>
              <div className="flex flex-col ml-5 w-[33%] max-md:ml-0 max-md:w-full">
                <div className="flex flex-col grow px-3 pt-3 pb-5 w-full text-base font-semibold leading-6 bg-white rounded-xl border border-solid border-zinc-100 text-zinc-600 max-md:mt-2.5">
                  <img
                    loading="lazy"
                    srcSet="https://cdn.builder.io/api/v1/image/assets/TEMP/c6488f657a932b682b41719c6734d7f22fb8792fb854ecbc601cae39d4276a6b?apiKey=706b7444b4d24b608a36b188095816f8&width=100 100w, https://cdn.builder.io/api/v1/image/assets/TEMP/c6488f657a932b682b41719c6734d7f22fb8792fb854ecbc601cae39d4276a6b?apiKey=706b7444b4d24b608a36b188095816f8&width=200 200w, https://cdn.builder.io/api/v1/image/assets/TEMP/c6488f657a932b682b41719c6734d7f22fb8792fb854ecbc601cae39d4276a6b?apiKey=706b7444b4d24b608a36b188095816f8&width=400 400w, https://cdn.builder.io/api/v1/image/assets/TEMP/c6488f657a932b682b41719c6734d7f22fb8792fb854ecbc601cae39d4276a6b?apiKey=706b7444b4d24b608a36b188095816f8&width=800 800w, https://cdn.builder.io/api/v1/image/assets/TEMP/c6488f657a932b682b41719c6734d7f22fb8792fb854ecbc601cae39d4276a6b?apiKey=706b7444b4d24b608a36b188095816f8&width=1200 1200w, https://cdn.builder.io/api/v1/image/assets/TEMP/c6488f657a932b682b41719c6734d7f22fb8792fb854ecbc601cae39d4276a6b?apiKey=706b7444b4d24b608a36b188095816f8&width=1600 1600w, https://cdn.builder.io/api/v1/image/assets/TEMP/c6488f657a932b682b41719c6734d7f22fb8792fb854ecbc601cae39d4276a6b?apiKey=706b7444b4d24b608a36b188095816f8&width=2000 2000w, https://cdn.builder.io/api/v1/image/assets/TEMP/c6488f657a932b682b41719c6734d7f22fb8792fb854ecbc601cae39d4276a6b?apiKey=706b7444b4d24b608a36b188095816f8&"
                    className="w-full aspect-[1.54]"
                  />
                  <div className="mt-6">
                    Enhancing Cognitive Growth: Strategies for Mental
                    Development
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="flex gap-1 justify-center self-center px-0.5 py-1.5 mt-12 text-xl font-semibold leading-7 text-center text-sky-500 rounded-lg max-md:mt-10">
            <div>Read more</div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/9997966c3f7d84ab1be7b4f12e5e21cd277902445b5e16c02aa59e76d02b304d?apiKey=706b7444b4d24b608a36b188095816f8&"
              className="shrink-0 my-auto w-4 aspect-square"
            />
          </div>
        </div>
      </div>
      <div className="flex z-10 justify-center items-center px-16 py-20 w-full bg-white max-md:px-5 max-md:max-w-full">
        <div className="flex flex-col mt-4 mb-1.5 w-full max-w-[1120px] max-md:max-w-full">
          <div className="flex flex-col self-start pl-4 border-l-2 border-sky-500 border-solid max-md:max-w-full">
            <div className="text-base leading-8 uppercase text-zinc-500 max-md:max-w-full">
              FAQ
            </div>
            <div className="text-4xl font-semibold leading-8 text-cyan-900 max-md:max-w-full">
              Questions about using RXPIN
            </div>
          </div>
          <div className="flex gap-2.5 justify-between px-9 py-3 mt-12 text-sm leading-5 rounded bg-slate-50 bg-opacity-70 text-zinc-600 max-md:flex-wrap max-md:px-5 max-md:mt-10 max-md:max-w-full">
            <div className="my-auto max-md:max-w-full">
              Dolor penatibus venenatis tristique consequat donec amet et.
              Venenatis senectus orci bibendum sit arcu facilisi.
            </div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/92894cdff4a02706a6c5ae6a93e46a6461bfd3e498c118dedcb6e3c558b57d0d?apiKey=706b7444b4d24b608a36b188095816f8&"
              className="shrink-0 w-6 aspect-square"
            />
          </div>
          <div className="flex gap-2.5 justify-between px-9 py-3 mt-6 text-sm leading-5 rounded bg-slate-50 bg-opacity-70 text-zinc-600 max-md:flex-wrap max-md:px-5 max-md:max-w-full">
            <div className="my-auto max-md:max-w-full">
              Dolor penatibus venenatis tristique consequat donec amet et.
              Venenatis senectus orci bibendum sit arcu facilisi.
            </div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/92894cdff4a02706a6c5ae6a93e46a6461bfd3e498c118dedcb6e3c558b57d0d?apiKey=706b7444b4d24b608a36b188095816f8&"
              className="shrink-0 w-6 aspect-square"
            />
          </div>
          <div className="flex gap-2.5 justify-between px-9 py-3 mt-6 text-sm leading-5 rounded bg-slate-50 bg-opacity-70 text-zinc-600 max-md:flex-wrap max-md:px-5 max-md:max-w-full">
            <div className="my-auto max-md:max-w-full">
              Dolor penatibus venenatis tristique consequat donec amet et.
              Venenatis senectus orci bibendum sit arcu facilisi.
            </div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/92894cdff4a02706a6c5ae6a93e46a6461bfd3e498c118dedcb6e3c558b57d0d?apiKey=706b7444b4d24b608a36b188095816f8&"
              className="shrink-0 w-6 aspect-square"
            />
          </div>
          <div className="flex gap-2.5 justify-between px-9 py-3 mt-6 text-sm leading-5 rounded bg-slate-50 bg-opacity-70 text-zinc-600 max-md:flex-wrap max-md:px-5 max-md:max-w-full">
            <div className="my-auto max-md:max-w-full">
              Dolor penatibus venenatis tristique consequat donec amet et.
              Venenatis senectus orci bibendum sit arcu facilisi.
            </div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/92894cdff4a02706a6c5ae6a93e46a6461bfd3e498c118dedcb6e3c558b57d0d?apiKey=706b7444b4d24b608a36b188095816f8&"
              className="shrink-0 w-6 aspect-square"
            />
          </div>
          <div className="flex gap-2.5 justify-between px-9 py-3 mt-6 text-sm leading-5 rounded bg-slate-50 bg-opacity-70 text-zinc-600 max-md:flex-wrap max-md:px-5 max-md:max-w-full">
            <div className="my-auto max-md:max-w-full">
              Dolor penatibus venenatis tristique consequat donec amet et.
              Venenatis senectus orci bibendum sit arcu facilisi.
            </div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/92894cdff4a02706a6c5ae6a93e46a6461bfd3e498c118dedcb6e3c558b57d0d?apiKey=706b7444b4d24b608a36b188095816f8&"
              className="shrink-0 w-6 aspect-square"
            />
          </div>
          <div className="flex gap-2.5 justify-between px-9 py-3 mt-6 text-sm leading-5 rounded bg-slate-50 bg-opacity-70 text-zinc-600 max-md:flex-wrap max-md:px-5 max-md:max-w-full">
            <div className="my-auto max-md:max-w-full">
              Dolor penatibus venenatis tristique consequat donec amet et.
              Venenatis senectus orci bibendum sit arcu facilisi.
            </div>
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/92894cdff4a02706a6c5ae6a93e46a6461bfd3e498c118dedcb6e3c558b57d0d?apiKey=706b7444b4d24b608a36b188095816f8&"
              className="shrink-0 w-6 aspect-square"
            />
          </div>
        </div>
      </div>
      <div className="flex justify-center items-center px-16 py-20 w-full text-xs leading-5 text-white bg-slate-900 max-md:px-5 max-md:max-w-full">
        <div className="flex gap-5 justify-between items-start my-4 max-w-full w-[951px] max-md:flex-wrap">
          <div className="flex flex-col text-sm leading-5 text-neutral-100">
            <img
              loading="lazy"
              src="https://cdn.builder.io/api/v1/image/assets/TEMP/8c6532484bfd25ba7983ddad4779f0f039a9fb44aa265fc6f416a0ed30c96db1?apiKey=706b7444b4d24b608a36b188095816f8&"
              className="max-w-full aspect-[5.26] w-[125px]"
            />
            <div className="mt-4">
              A specialized communication and synchronization platform designed
              for therapists, patients, and guardians within the neuro-divergent
              community.
            </div>
          </div>
          <div className="flex flex-col font-medium">
            <div className="text-sm font-semibold leading-5 text-white">
              Connect with us
            </div>
            <div className="flex gap-2 mt-4 text-white">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/1444276e172cb0f3390c277c0902f2f351118d954abb0814c30ef5e18f6df7c1?apiKey=706b7444b4d24b608a36b188095816f8&"
                className="shrink-0 self-start w-4 aspect-square"
              />
              <div>Get connected through LinkedIn</div>
            </div>
            <div className="flex gap-3 mt-4">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/a95a44517c7fc406e6424e399ea4819537a06f92739d0948dc3da0ec657613bd?apiKey=706b7444b4d24b608a36b188095816f8&"
                className="shrink-0 self-start w-4 aspect-square"
              />
              <div className="justify-center py-1">
                Building 123, ABC Street, Lalitpur, Nepal, 44700{" "}
              </div>
            </div>
            <div className="flex gap-3 mt-4">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/823a4c53549cfb121bf984b1ed6cdbc3ae8180e5dbeebaf8fbe9a26cd9b8a42e?apiKey=706b7444b4d24b608a36b188095816f8&"
                className="shrink-0 self-start w-4 aspect-square"
              />
              <div className="justify-center py-1">
                +977-9876543211 | +977-01- 5443123
              </div>
            </div>
            <div className="flex gap-3 mt-4 whitespace-nowrap">
              <img
                loading="lazy"
                src="https://cdn.builder.io/api/v1/image/assets/TEMP/23247643e19237fbf1841aef8c621c623e90288e4801d10cd949dfd2ffb99b38?apiKey=706b7444b4d24b608a36b188095816f8&"
                className="shrink-0 self-start w-4 aspect-square"
              />
              <div className="justify-center py-1">connect@rxpin.com</div>
            </div>
          </div>
          <div className="flex flex-col self-stretch">
            <div className="text-sm font-semibold leading-5">Website</div>
            <div className="mt-4">Home</div>
            <div className="mt-4">Features</div>
            <div className="mt-4">About us</div>
            <div className="mt-4">Contact Us</div>
            <div className="mt-4">Blogs</div>
            <div className="mt-4">FAQ</div>
          </div>
        </div>
      </div>
    </div>
  );
}
